version: "3"
services:
  impfbot:
    container_name: impfbot
    image: ghcr.io/sibalzer/impfbot:latest
    restart: unless-stopped
    volumes:
      - ./config.ini:/config.ini    # must exist before launching
    environment:
      - TZ=Europe/Berlin
